<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Yosamu MUHANZI">

<title>Topic 4: Survival Outcomes of AIDS Patients in Australia</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="topic4_aids_survival_files/libs/clipboard/clipboard.min.js"></script>
<script src="topic4_aids_survival_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="topic4_aids_survival_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="topic4_aids_survival_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="topic4_aids_survival_files/libs/quarto-html/popper.min.js"></script>
<script src="topic4_aids_survival_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="topic4_aids_survival_files/libs/quarto-html/anchor.min.js"></script>
<link href="topic4_aids_survival_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="topic4_aids_survival_files/libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="topic4_aids_survival_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="topic4_aids_survival_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="topic4_aids_survival_files/libs/bootstrap/bootstrap-6a8e6d95bfcd174082ff54166b04dcf7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a>
  <ul class="collapse">
  <li><a href="#objective" id="toc-objective" class="nav-link" data-scroll-target="#objective"><span class="header-section-number">1.1</span> Objective</a></li>
  <li><a href="#load-the-dataset" id="toc-load-the-dataset" class="nav-link" data-scroll-target="#load-the-dataset"><span class="header-section-number">1.2</span> Load the Dataset</a></li>
  </ul></li>
  <li><a href="#create-survival-variables" id="toc-create-survival-variables" class="nav-link" data-scroll-target="#create-survival-variables"><span class="header-section-number">2</span> Create Survival Variables</a></li>
  <li><a href="#exploratory-data-analysis-eda" id="toc-exploratory-data-analysis-eda" class="nav-link" data-scroll-target="#exploratory-data-analysis-eda"><span class="header-section-number">3</span> Exploratory Data Analysis (EDA)</a>
  <ul class="collapse">
  <li><a href="#age-distribution" id="toc-age-distribution" class="nav-link" data-scroll-target="#age-distribution"><span class="header-section-number">3.1</span> Age Distribution</a></li>
  <li><a href="#sex-distribution" id="toc-sex-distribution" class="nav-link" data-scroll-target="#sex-distribution"><span class="header-section-number">3.2</span> Sex Distribution</a></li>
  <li><a href="#follow-up-times-for-aids-patients" id="toc-follow-up-times-for-aids-patients" class="nav-link" data-scroll-target="#follow-up-times-for-aids-patients"><span class="header-section-number">3.3</span> Follow-up Times for AIDS Patients</a></li>
  <li><a href="#survival-time-distribution" id="toc-survival-time-distribution" class="nav-link" data-scroll-target="#survival-time-distribution"><span class="header-section-number">3.4</span> Survival Time Distribution</a></li>
  </ul></li>
  <li><a href="#model-formulation" id="toc-model-formulation" class="nav-link" data-scroll-target="#model-formulation"><span class="header-section-number">4</span> Model Formulation</a>
  <ul class="collapse">
  <li><a href="#kaplanmeier-survival-curve" id="toc-kaplanmeier-survival-curve" class="nav-link" data-scroll-target="#kaplanmeier-survival-curve"><span class="header-section-number">4.1</span> Kaplan–Meier Survival Curve</a></li>
  <li><a href="#kaplanmeier-survival-curve-by-sex" id="toc-kaplanmeier-survival-curve-by-sex" class="nav-link" data-scroll-target="#kaplanmeier-survival-curve-by-sex"><span class="header-section-number">4.2</span> Kaplan–Meier survival curve by sex</a></li>
  <li><a href="#log-rank-test" id="toc-log-rank-test" class="nav-link" data-scroll-target="#log-rank-test"><span class="header-section-number">4.3</span> Log-Rank Test</a></li>
  <li><a href="#cox-proportional-hazards-model" id="toc-cox-proportional-hazards-model" class="nav-link" data-scroll-target="#cox-proportional-hazards-model"><span class="header-section-number">4.4</span> Cox Proportional Hazards Model</a></li>
  <li><a href="#hazard-ratio-table" id="toc-hazard-ratio-table" class="nav-link" data-scroll-target="#hazard-ratio-table"><span class="header-section-number">4.5</span> Hazard Ratio Table</a></li>
  <li><a href="#proportional-hazards-assumption" id="toc-proportional-hazards-assumption" class="nav-link" data-scroll-target="#proportional-hazards-assumption"><span class="header-section-number">4.6</span> Proportional Hazards Assumption</a></li>
  <li><a href="#schoenfeld-residual-plot" id="toc-schoenfeld-residual-plot" class="nav-link" data-scroll-target="#schoenfeld-residual-plot"><span class="header-section-number">4.7</span> Schoenfeld Residual Plot</a></li>
  </ul></li>
  <li><a href="#recommendations" id="toc-recommendations" class="nav-link" data-scroll-target="#recommendations"><span class="header-section-number">5</span> Recommendations</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">6</span> Conclusion</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Topic 4: Survival Outcomes of AIDS Patients in Australia</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Yosamu MUHANZI </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>Acquired Immunodeficiency Syndrome (AIDS) is a disease that damages the immune system and makes the body more vulnerable to infections and other illnesses. Although medical treatment has improved over the years, AIDS still causes many deaths around the world.</p>
<p>Studying survival after diagnosis helps researchers understand how long patients live after developing the disease and what factors influence survival. Some patients die during follow-up while others are still alive at the end of the study. When this happens, the outcome is called <strong>time-to-event data</strong>, and survival analysis is the appropriate statistical method.</p>
<p>This project investigates survival outcomes of AIDS patients in Australia. The analysis focuses on how factors such as age, sex, state of residence, and transmission category affect survival time.</p>
<p>The survival analysis methods used in this project are :</p>
<ul>
<li>Kaplan–Meier survival estimation</li>
<li>Log-rank test</li>
<li>Cox proportional hazards model</li>
<li>Proportional hazards assumption test</li>
</ul>
<p>These methods help describe survival patterns and identify factors associated with the risk of death.</p>
<section id="objective" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="objective"><span class="header-section-number">1.1</span> Objective</h2>
<p>The main objective of this study is to investigate the survival outcomes of AIDS patients in Australia.</p>
<p>The specific objectives are:</p>
<ul>
<li>To explore the dataset using descriptive statistics and graphs.</li>
<li>To estimate survival probabilities using Kaplan–Meier curves.</li>
<li>To compare survival between groups using the log-rank test.</li>
<li>To identify factors affecting survival using the Cox proportional hazards model.</li>
<li>To check whether the proportional hazards assumption is satisfied.</li>
</ul>
</section>
<section id="load-the-dataset" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="load-the-dataset"><span class="header-section-number">1.2</span> Load the Dataset</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survival)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(Aids2)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(Aids2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   2843 obs. of  7 variables:
 $ state  : Factor w/ 4 levels "NSW","Other",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ sex    : Factor w/ 2 levels "F","M": 2 2 2 2 2 2 2 2 2 2 ...
 $ diag   : int  10905 11029 9551 9577 10015 9971 10746 10042 10464 10439 ...
 $ death  : int  11081 11096 9983 9654 10290 10344 11135 11069 10956 10873 ...
 $ status : Factor w/ 2 levels "A","D": 2 2 2 2 2 2 2 2 2 2 ...
 $ T.categ: Factor w/ 8 levels "hs","hsid","id",..: 1 1 1 5 1 1 8 1 1 2 ...
 $ age    : int  35 53 42 44 39 36 36 31 26 27 ...</code></pre>
</div>
</div>
<p><strong>Interpretation</strong></p>
<p>The dataset contains information about AIDS patients in Australia.</p>
<p>Each row represents one patient and includes information such as:</p>
<ul>
<li>sex</li>
<li>age</li>
<li>state of residence</li>
<li>transmission category</li>
<li>diagnosis date</li>
<li>death date</li>
<li>survival status</li>
</ul>
</section>
</section>
<section id="create-survival-variables" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Create Survival Variables</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"Aids2"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>aids <span class="ot">&lt;-</span> Aids2 <span class="sc">|&gt;</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">survival_time =</span> <span class="fu">as.numeric</span>(death <span class="sc">-</span> diag),</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">survival_years =</span> survival_time <span class="sc">/</span> <span class="fl">365.25</span>,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">event =</span> <span class="fu">ifelse</span>(status <span class="sc">==</span> <span class="st">"D"</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(aids)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  state sex  diag death status T.categ age survival_time survival_years event
1   NSW   M 10905 11081      D      hs  35           176      0.4818617     1
2   NSW   M 11029 11096      D      hs  53            67      0.1834360     1
3   NSW   M  9551  9983      D      hs  42           432      1.1827515     1
4   NSW   M  9577  9654      D    haem  44            77      0.2108145     1
5   NSW   M 10015 10290      D      hs  39           275      0.7529090     1
6   NSW   M  9971 10344      D      hs  36           373      1.0212183     1</code></pre>
</div>
</div>
<p><strong>Interpretation</strong></p>
<p>The variable survival_time gives the number of days each patient survived after diagnosis, calculated as death minus diag. The variable survival_years changes this survival time into years by dividing by 365.25, which makes the time easier to understand. The variable event shows whether the patient died or not, where 1 means death occurred and 0 means censored or still alive.</p>
</section>
<section id="exploratory-data-analysis-eda" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Exploratory Data Analysis (EDA)</h1>
<p>Exploratory data analysis (EDA) helps us understand the AIDS dataset before doing the survival analysis. In our study, it is used to look at important variables such as age, sex, state, transmission category, survival time, and event status. It helps us see how the patients are grouped, check for missing values, and observe general patterns in the data. This is important because it gives us a simple picture of the data before we use the Kaplan–Meier curve, log-rank test, and Cox model.</p>
<section id="age-distribution" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="age-distribution"><span class="header-section-number">3.1</span> Age Distribution</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(aids, <span class="fu">aes</span>(age)) <span class="sc">+</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">bins =</span> <span class="dv">30</span>) <span class="sc">+</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Age"</span>, <span class="at">x =</span> <span class="st">"Age"</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="topic4_aids_survival_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation</strong></p>
<p>The histogram shows the distribution of age and the number of patients in each age group. Most patients are between about 25 and 45 years old, with the highest number around 30 to 40 years. There are fewer patients at very young ages and fewer at older ages above about 60 years. This means that in this study, AIDS patients were mainly young and middle-aged adults</p>
</section>
<section id="sex-distribution" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="sex-distribution"><span class="header-section-number">3.2</span> Sex Distribution</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(aids, <span class="fu">aes</span>(sex)) <span class="sc">+</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill=</span><span class="st">"orange"</span>) <span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Sex Distribution"</span>, <span class="at">x=</span><span class="st">"Sex"</span>, <span class="at">y=</span><span class="st">"Count"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="topic4_aids_survival_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>interpretantion</strong></p>
<p>The bar chart compares sex (male and female) with the number of patients. It shows that the number of male patients is much higher than female patients. a small number of females are in the dataset, while most patients are male. This means that in this study, AIDS cases were mainly observed in males compared with females.</p>
</section>
<section id="follow-up-times-for-aids-patients" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="follow-up-times-for-aids-patients"><span class="header-section-number">3.3</span> Follow-up Times for AIDS Patients</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"Aids2"</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>aids <span class="ot">&lt;-</span> Aids2</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>aids <span class="ot">&lt;-</span> aids <span class="sc">%&gt;%</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">survival_time =</span> <span class="fu">as.numeric</span>(death <span class="sc">-</span> diag),</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">survival_years =</span> survival_time <span class="sc">/</span> <span class="fl">365.25</span>,</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">outcome =</span> <span class="fu">ifelse</span>(status <span class="sc">==</span> <span class="st">"D"</span>, <span class="st">"Death"</span>, <span class="st">"Censored"</span>)</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>aids_swim <span class="ot">&lt;-</span> aids <span class="sc">%&gt;%</span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">n =</span> <span class="dv">30</span>) <span class="sc">%&gt;%</span></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(survival_years) <span class="sc">%&gt;%</span></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">patient_id =</span> <span class="fu">row_number</span>())</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(aids_swim, <span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">factor</span>(patient_id))) <span class="sc">+</span></span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">0</span>, <span class="at">xend =</span> survival_years, <span class="at">yend =</span> <span class="fu">factor</span>(patient_id)),</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">linewidth =</span> <span class="dv">1</span>,</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"steelblue"</span></span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> survival_years, <span class="at">shape =</span> outcome, <span class="at">color =</span> outcome),</span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">3</span></span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_shape_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Death"</span> <span class="ot">=</span> <span class="dv">17</span>, <span class="st">"Censored"</span> <span class="ot">=</span> <span class="dv">16</span>)) <span class="sc">+</span></span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Death"</span> <span class="ot">=</span> <span class="st">"red"</span>, <span class="st">"Censored"</span> <span class="ot">=</span> <span class="st">"black"</span>)) <span class="sc">+</span></span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Swimmer Plot of Follow-up Times for AIDS Patients"</span>,</span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Time from diagnosis (years)"</span>,</span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Patient ID"</span>,</span>
<span id="cb7-37"><a href="#cb7-37" aria-hidden="true" tabindex="-1"></a>    <span class="at">shape =</span> <span class="st">"Outcome"</span>,</span>
<span id="cb7-38"><a href="#cb7-38" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Outcome"</span></span>
<span id="cb7-39"><a href="#cb7-39" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb7-40"><a href="#cb7-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb7-41"><a href="#cb7-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb7-42"><a href="#cb7-42" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb7-43"><a href="#cb7-43" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>)</span>
<span id="cb7-44"><a href="#cb7-44" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="topic4_aids_survival_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation</strong></p>
<p>The swimmer plot shows the follow-up time for each AIDS patient. The x-axis shows time in years, and the y-axis shows patients. Each line shows how long a patient was followed. A red triangle means death, and a black dot means the patient was censored. The plot shows that some patients had short follow-up times, while others were followed for several years. It also shows that deaths and censored cases occurred at different times.</p>
</section>
<section id="survival-time-distribution" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="survival-time-distribution"><span class="header-section-number">3.4</span> Survival Time Distribution</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(aids, <span class="fu">aes</span>(survival_years)) <span class="sc">+</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill=</span><span class="st">"darkgreen"</span>, <span class="at">bins=</span><span class="dv">30</span>) <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Distribution of Survival Time"</span>, <span class="at">x=</span><span class="st">"Years"</span>, <span class="at">y=</span><span class="st">"Count"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="topic4_aids_survival_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation</strong></p>
<p>The histogram shows survival time in years and the number of patients. It shows that many patients survived for 0 to 2 years after diagnosis. As survival time increases, the number of patients becomes smaller. This means most patients had short survival time, and only a few had long survival time.</p>
</section>
</section>
<section id="model-formulation" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Model Formulation</h1>
<p>Survival analysis studies the time until an event occurs.</p>
<p>The survival function is defined as:</p>
<p>S(t) = P(T &gt; t)</p>
<p>This represents the probability that a patient survives longer than time t.</p>
<p>The Cox proportional hazards model is written as:</p>
<p>h(t|X) = h₀(t) exp(β₁X₁ + β₂X₂ + …)</p>
<p>where:</p>
<ul>
<li>h(t|X) is the hazard of death</li>
<li>h₀(t) is the baseline hazard</li>
<li>X represents explanatory variables</li>
</ul>
<p>The predictors used in this study are:</p>
<ul>
<li>age</li>
<li>sex</li>
<li>state</li>
<li>transmission category</li>
</ul>
<section id="kaplanmeier-survival-curve" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="kaplanmeier-survival-curve"><span class="header-section-number">4.1</span> Kaplan–Meier Survival Curve</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survival)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survminer)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"Aids2"</span>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>aids <span class="ot">&lt;-</span> Aids2 <span class="sc">|&gt;</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">survival_time =</span> <span class="fu">as.numeric</span>(death <span class="sc">-</span> diag),</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">survival_years =</span> survival_time <span class="sc">/</span> <span class="fl">365.25</span>,</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">event =</span> <span class="fu">ifelse</span>(status <span class="sc">==</span> <span class="st">"D"</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>km_fit <span class="ot">&lt;-</span> <span class="fu">survfit</span>(<span class="fu">Surv</span>(survival_years, event) <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> aids)</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggsurvplot</span>(</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>  km_fit,</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> aids,</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">conf.int =</span> <span class="cn">TRUE</span>,</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">risk.table =</span> <span class="cn">TRUE</span>,</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Time (Years)"</span>,</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Survival Probability"</span>,</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">title =</span> <span class="st">"Kaplan-Meier Survival Curve"</span></span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="topic4_aids_survival_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation</strong></p>
<p>The Kaplan–Meier curve shows that the survival probability of AIDS patients decreases over time. At the start, all 2843 patients were alive, so the survival probability begins near 1. As time goes on, the curve keeps going down, which means more patients die during follow-up. By around 2 years, survival has dropped a lot, and after 4 to 6 years only a small number of patients are still alive. The number at risk also becomes smaller over time, from 2843 at the start to 459 at 2 years, 47 at 4 years, and 6 at 6 years. This shows that survival became lower as follow-up time increased.</p>
</section>
<section id="kaplanmeier-survival-curve-by-sex" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="kaplanmeier-survival-curve-by-sex"><span class="header-section-number">4.2</span> Kaplan–Meier survival curve by sex</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survival)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survminer)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"Aids2"</span>)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>aids <span class="ot">&lt;-</span> Aids2</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>aids <span class="ot">&lt;-</span> aids <span class="sc">%&gt;%</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">survival_time =</span> <span class="fu">as.numeric</span>(death <span class="sc">-</span> diag),</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">survival_years =</span> survival_time <span class="sc">/</span> <span class="fl">365.25</span>,</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">event =</span> <span class="fu">ifelse</span>(status <span class="sc">==</span> <span class="st">"D"</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>aids<span class="sc">$</span>sex <span class="ot">&lt;-</span> <span class="fu">factor</span>(aids<span class="sc">$</span>sex, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"F"</span>, <span class="st">"M"</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Female"</span>, <span class="st">"Male"</span>))</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>km_sex <span class="ot">&lt;-</span> <span class="fu">survfit</span>(<span class="fu">Surv</span>(survival_years, event) <span class="sc">~</span> sex, <span class="at">data =</span> aids)</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsurvplot</span>(</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>  km_sex,</span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> aids,</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">risk.table =</span> <span class="cn">TRUE</span>,</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">conf.int =</span> <span class="cn">FALSE</span>,</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">pval =</span> <span class="cn">TRUE</span>,</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">risk.table.y.text =</span> <span class="cn">TRUE</span>,</span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>  <span class="at">risk.table.y.text.col =</span> <span class="cn">TRUE</span>,</span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a>  <span class="at">risk.table.col =</span> <span class="st">"strata"</span>,</span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a>  <span class="at">risk.table.height =</span> <span class="fl">0.28</span>,</span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a>  <span class="at">break.time.by =</span> <span class="dv">1</span>,</span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Time (years)"</span>,</span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Survival probability"</span>,</span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a>  <span class="at">title =</span> <span class="st">"Survival by Sex"</span>,</span>
<span id="cb10-34"><a href="#cb10-34" aria-hidden="true" tabindex="-1"></a>  <span class="at">legend.title =</span> <span class="st">"Sex"</span>,</span>
<span id="cb10-35"><a href="#cb10-35" aria-hidden="true" tabindex="-1"></a>  <span class="at">legend.labs =</span> <span class="fu">c</span>(<span class="st">"Female"</span>, <span class="st">"Male"</span>),</span>
<span id="cb10-36"><a href="#cb10-36" aria-hidden="true" tabindex="-1"></a>  <span class="at">tables.theme =</span> <span class="fu">theme_cleantable</span>(),</span>
<span id="cb10-37"><a href="#cb10-37" aria-hidden="true" tabindex="-1"></a>  <span class="at">ggtheme =</span> <span class="fu">theme_bw</span>(),</span>
<span id="cb10-38"><a href="#cb10-38" aria-hidden="true" tabindex="-1"></a>  <span class="at">fontsize =</span> <span class="dv">4</span></span>
<span id="cb10-39"><a href="#cb10-39" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="topic4_aids_survival_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation</strong></p>
<p>The Kaplan–Meier survival curve compares survival between male and female AIDS patients. At the beginning of the study, the survival probability for both groups is close to 1, meaning almost all patients were alive at the start. As time increases, the survival probability decreases for both males and females, showing that deaths occur over time. The female survival curve is slightly higher than the male curve in several parts of the graph, suggesting that females may survive a little longer than males. However, the difference between the two groups is small. The log-rank test gives a p-value of 0.36, which is greater than 0.05, indicating that the difference in survival between males and females is not statistically significant</p>
</section>
<section id="log-rank-test" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="log-rank-test"><span class="header-section-number">4.3</span> Log-Rank Test</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">survdiff</span>(<span class="fu">Surv</span>(survival_years, event) <span class="sc">~</span> sex, <span class="at">data =</span> aids)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
survdiff(formula = Surv(survival_years, event) ~ sex, data = aids)

              N Observed Expected (O-E)^2/E (O-E)^2/V
sex=Female   89       53     59.9     0.795     0.826
sex=Male   2754     1708   1701.1     0.028     0.826

 Chisq= 0.8  on 1 degrees of freedom, p= 0.4 </code></pre>
</div>
</div>
<p><strong>Interpretation</strong></p>
<p>The log-rank test shows that there is no significant difference in survival between male and female AIDS patients. Although females had 53 observed deaths and males had 1708, the p-value is 0.4, which is greater than 0.05. This means the difference in survival between the two groups is small and may be due to chance. Therefore, sex does not seem to have an important effect on survival time in this study</p>
</section>
<section id="cox-proportional-hazards-model" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="cox-proportional-hazards-model"><span class="header-section-number">4.4</span> Cox Proportional Hazards Model</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>cox_model <span class="ot">&lt;-</span> <span class="fu">coxph</span>(</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Surv</span>(survival_years, event) <span class="sc">~</span> age <span class="sc">+</span> sex <span class="sc">+</span> state <span class="sc">+</span> T.categ,</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> aids</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cox_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
coxph(formula = Surv(survival_years, event) ~ age + sex + state + 
    T.categ, data = aids)

  n= 2843, number of events= 1761 

                   coef exp(coef)  se(coef)      z Pr(&gt;|z|)    
age            0.013204  1.013291  0.002497  5.288 1.24e-07 ***
sexMale       -0.046706  0.954367  0.175017 -0.267  0.78957    
stateOther    -0.088449  0.915349  0.089592 -0.987  0.32352    
stateQLD       0.151085  1.163095  0.087700  1.723  0.08493 .  
stateVIC      -0.019206  0.980977  0.061291 -0.313  0.75401    
T.categhsid   -0.082573  0.920745  0.152097 -0.543  0.58720    
T.categid     -0.494065  0.610141  0.246611 -2.003  0.04513 *  
T.categhet    -0.740869  0.476699  0.263977 -2.807  0.00501 ** 
T.categhaem    0.341663  1.407286  0.188477  1.813  0.06987 .  
T.categblood   0.348810  1.417380  0.135163  2.581  0.00986 ** 
T.categmother  0.264308  1.302530  0.588489  0.449  0.65334    
T.categother   0.072621  1.075323  0.164190  0.442  0.65827    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

              exp(coef) exp(-coef) lower .95 upper .95
age              1.0133     0.9869    1.0083    1.0183
sexMale          0.9544     1.0478    0.6772    1.3449
stateOther       0.9153     1.0925    0.7679    1.0911
stateQLD         1.1631     0.8598    0.9794    1.3812
stateVIC         0.9810     1.0194    0.8699    1.1062
T.categhsid      0.9207     1.0861    0.6834    1.2405
T.categid        0.6101     1.6390    0.3763    0.9893
T.categhet       0.4767     2.0978    0.2841    0.7997
T.categhaem      1.4073     0.7106    0.9726    2.0362
T.categblood     1.4174     0.7055    1.0875    1.8473
T.categmother    1.3025     0.7677    0.4110    4.1277
T.categother     1.0753     0.9300    0.7794    1.4835

Concordance= 0.567  (se = 0.008 )
Likelihood ratio test= 70.27  on 12 df,   p=3e-10
Wald test            = 71.5  on 12 df,   p=2e-10
Score (logrank) test = 72.67  on 12 df,   p=1e-10</code></pre>
</div>
</div>
<p><strong>Interpretation</strong></p>
<p>The Cox proportional hazards model shows that age is an important factor in survival, because its hazard ratio is 1.013 with p &lt; 0.001, meaning that for each one-year increase in age, the risk of death increases by about 1.3% while holding other factors constant. Sex is not significant (p = 0.790), so survival does not differ importantly between males and females after adjustment for other variables. For state, none of the categories is clearly significant at the 5% level, although Queensland shows a slightly higher risk than the reference group (HR = 1.163, p = 0.085), which is only weak evidence. For transmission category, some groups differ significantly: patients in id have a lower risk of death (HR = 0.61, p = 0.045) and those in het also have a lower risk (HR = 0.48, p = 0.005) compared with the reference category, while patients in blood have a higher risk (HR = 1.42, p = 0.010). The overall model is statistically significant (Likelihood ratio test p &lt; 0.001), which means the variables in the model help explain survival, although the concordance of 0.567 suggests the model has only a modest ability to predict who survives longer</p>
</section>
<section id="hazard-ratio-table" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="hazard-ratio-table"><span class="header-section-number">4.5</span> Hazard Ratio Table</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(cox_model, <span class="at">exponentiate =</span> <span class="cn">TRUE</span>, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 7
   term          estimate std.error statistic     p.value conf.low conf.high
   &lt;chr&gt;            &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
 1 age              1.01    0.00250     5.29  0.000000124    1.01      1.02 
 2 sexMale          0.954   0.175      -0.267 0.790          0.677     1.34 
 3 stateOther       0.915   0.0896     -0.987 0.324          0.768     1.09 
 4 stateQLD         1.16    0.0877      1.72  0.0849         0.979     1.38 
 5 stateVIC         0.981   0.0613     -0.313 0.754          0.870     1.11 
 6 T.categhsid      0.921   0.152      -0.543 0.587          0.683     1.24 
 7 T.categid        0.610   0.247      -2.00  0.0451         0.376     0.989
 8 T.categhet       0.477   0.264      -2.81  0.00501        0.284     0.800
 9 T.categhaem      1.41    0.188       1.81  0.0699         0.973     2.04 
10 T.categblood     1.42    0.135       2.58  0.00986        1.09      1.85 
11 T.categmother    1.30    0.588       0.449 0.653          0.411     4.13 
12 T.categother     1.08    0.164       0.442 0.658          0.779     1.48 </code></pre>
</div>
</div>
</section>
<section id="proportional-hazards-assumption" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="proportional-hazards-assumption"><span class="header-section-number">4.6</span> Proportional Hazards Assumption</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>ph_test <span class="ot">&lt;-</span> <span class="fu">cox.zph</span>(cox_model)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>ph_test</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        chisq df       p
age     22.71  1 1.9e-06
sex      2.72  1  0.0991
state   17.03  3  0.0007
T.categ 34.27  7 1.5e-05
GLOBAL  59.69 12 2.6e-08</code></pre>
</div>
</div>
<p><strong>Interpretation</strong></p>
<p>The proportional hazards test checks whether the effect of each variable stays the same over time in the Cox model. the global p-value is 2.6 × 10⁻⁸, which is less than 0.05, so the model does not fully satisfy this assumption. This means some variables change their effect over time. In particular, age (p = 1.9 × 10⁻⁶), state (p = 0.0007), and transmission category (p = 1.5 × 10⁻⁵) do not satisfy the assumption, so their effects on survival are not constant during follow-up. However, sex (p = 0.0991) is greater than 0.05, so sex does not show a serious problem and its effect can be treated as fairly constant over time. Overall, this means the Cox model is useful, but it should be interpreted carefully because some predictors do not meet the proportional hazards assumption.</p>
</section>
<section id="schoenfeld-residual-plot" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="schoenfeld-residual-plot"><span class="header-section-number">4.7</span> Schoenfeld Residual Plot</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survival)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"Aids2"</span>)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>aids <span class="ot">&lt;-</span> Aids2</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>aids <span class="ot">&lt;-</span> aids <span class="sc">%&gt;%</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">survival_time =</span> <span class="fu">as.numeric</span>(death <span class="sc">-</span> diag),</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">survival_years =</span> survival_time <span class="sc">/</span> <span class="fl">365.25</span>,</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">event =</span> <span class="fu">ifelse</span>(status <span class="sc">==</span> <span class="st">"D"</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>cox_model <span class="ot">&lt;-</span> <span class="fu">coxph</span>(</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Surv</span>(survival_years, event) <span class="sc">~</span> age <span class="sc">+</span> sex <span class="sc">+</span> state <span class="sc">+</span> T.categ,</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> aids</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>ph_test <span class="ot">&lt;-</span> <span class="fu">cox.zph</span>(cox_model)</span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(ph_test<span class="sc">$</span>table, <span class="dv">6</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            chisq df        p
age     22.707210  1 0.000002
sex      2.719302  1 0.099141
state   17.033725  3 0.000696
T.categ 34.274426  7 0.000015
GLOBAL  59.689297 12 0.000000</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ph_test[<span class="dv">1</span>], <span class="at">main =</span> <span class="fu">paste</span>(<span class="st">"Age: p ="</span>, <span class="fu">signif</span>(ph_test<span class="sc">$</span>table[<span class="st">"age"</span>, <span class="st">"p"</span>], <span class="dv">4</span>)),</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ph_test[<span class="dv">2</span>], <span class="at">main =</span> <span class="fu">paste</span>(<span class="st">"Sex: p ="</span>, <span class="fu">signif</span>(ph_test<span class="sc">$</span>table[<span class="st">"sex"</span>, <span class="st">"p"</span>], <span class="dv">4</span>)),</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ph_test[<span class="dv">3</span>], <span class="at">main =</span> <span class="fu">paste</span>(<span class="st">"State: p ="</span>, <span class="fu">signif</span>(ph_test<span class="sc">$</span>table[<span class="st">"state"</span>, <span class="st">"p"</span>], <span class="dv">4</span>)),</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ph_test[<span class="dv">4</span>], <span class="at">main =</span> <span class="fu">paste</span>(<span class="st">"Transmission category: p ="</span>, <span class="fu">signif</span>(ph_test<span class="sc">$</span>table[<span class="st">"T.categ"</span>, <span class="st">"p"</span>], <span class="dv">4</span>)),</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a><span class="fu">mtext</span>(</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">paste</span>(<span class="st">"Global Schoenfeld Test p ="</span>, <span class="fu">signif</span>(ph_test<span class="sc">$</span>table[<span class="st">"GLOBAL"</span>, <span class="st">"p"</span>], <span class="dv">4</span>)),</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">outer =</span> <span class="cn">TRUE</span>,</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">line =</span> <span class="sc">-</span><span class="dv">2</span>,</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">cex =</span> <span class="fl">1.1</span></span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="topic4_aids_survival_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Interpretation</strong></p>
<p>The Schoenfeld residual test was used to check the proportional hazards assumption of the Cox model. The global test is significant (p = 2.57 × 10⁻⁸), which suggests that the proportional hazards assumption may not hold for the model. Age, state, and transmission category have p-values less than 0.05, indicating that their effects may change over time. However, sex has a p-value greater than 0.05, suggesting that the proportional hazards assumption is reasonable for this variable.</p>
</section>
</section>
<section id="recommendations" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Recommendations</h1>
<p>The government should strengthen early HIV testing and early treatment programs. The analysis showed that survival probability decreases over time after diagnosis. Detecting HIV earlier and starting treatment quickly can help patients live longer and improve their quality of life.</p>
<p>Health services should give special attention to older patients. The results showed that age increases the risk of death, meaning older patients have poorer survival outcomes. Regular monitoring and targeted healthcare support for older patients may help reduce this risk.</p>
<p>Prevention programs should focus on major transmission groups. The study showed that some transmission categories have different levels of risk. Public health programs should continue to promote awareness, safe behaviors, and prevention strategies for high-risk groups to reduce new infections.</p>
<p>The government should improve long-term care and follow-up for AIDS patients. Since survival decreases over time, continuous medical care, treatment support, and regular monitoring are important to improve patient outcomes.</p>
<p>The government should strengthen data collection and monitoring systems for HIV/AIDS patients. Better data can help health authorities understand survival patterns and design more effective policies and healthcare programs.</p>
</section>
<section id="conclusion" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Conclusion</h1>
<p>This study examined the survival outcomes of AIDS patients in Australia using the Aids2 dataset. The analysis showed that the survival probability of AIDS patients decreases over time after diagnosis. Many patients survived for a short period, while fewer patients survived for many years.</p>
<p>The results showed that age is an important factor affecting survival. Older patients have a higher risk of death compared with younger patients. The analysis also showed that some transmission categories have different levels of risk, meaning that survival outcomes are not the same for all groups.</p>
<p>The comparison between males and females showed that females appeared to have slightly better survival, but the difference was not statistically significant. This means sex did not have a strong effect on survival in this study.</p>
<p>The results show that survival of AIDS patients is strongly related to age and transmission category. Survival becomes lower as more time passes after diagnosis. These findings help us better understand how long patients live after diagnosis and can help health authorities plan better treatment and care programs for AIDS patients.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>